import { Location } from './location.model';
export interface Clinic {
  id: number;
  organizationName: string;
  organizationContact: string;
  contactPersonName: string;
  contactPersonTitle: string;
  contactEmail: string;
  listedOnCra: string;
  visibleOnNceo: string;
  alternateContactName?: string;
  alternateContactEmail?: string;
  alternateContactPhone?: string;
  publicInfo: string;
  clinicTypes: string;
  wheelchairAccessible?: boolean;
  servePeopleFrom: string;
  catchmentArea?: string;
  monthsOffered: string;
  hoursOfOperation?: string;
  yearRoundService: boolean;
  populationServed?: string;
  serviceLanguages?: string;
  taxYearsPrepared: string;
  residencyTaxYear: string;
  servePeople: string;
  specialServices?: string;
  bookingProcess: string;
  bookingDaysHours: string;
  bookingContactPhone?: string;
  bookingContactEmail?: string;
  onlineBookingLink?: string;
  usefulOnlineBooking?: string;
  requiredDocuments?: string;
  helpWithMissingDocs: string;
  taxPreparers?: string;
  taxFilers?: string;
  volunteerRoles?: string;
  clinicCapacity?: string;
  additionalSupport?: string;
  comments?: string;
  createdDate: string;
  updatedDate: string;
  locations: Location[];
}

