import { Location } from './location.model';
export interface Clinic {
  [key: string]: any;
  id: number;
  organizationName: string;
  organisationWebsite: string;
  organisationalEmail: string;
  contactPersonName: string;
  contactPersonTitle: string;
  contactEmail: string;
  appointmentAvailability: string;
  listedOnCra: string;
  visibleOnNceo: string;
  alternateContactName?: string;
  alternateContactEmail?: string;
  alternateContactTitle?: string;
  alternateContactPhone?: string;
  publicInfo: string;
  clinicTypes: string | string[];
  wheelchairAccessible?: string;
  servePeopleFrom: string;
  catchmentArea: string;
  monthsOffered: string | string[];
  hoursAndDate: string;
  hoursOfOperation: string | string[];
  daysOfOperation: string | string[];
  yearRoundService: string;
  populationServed?: string | string[];
  serviceLanguages: string | string[];
  taxYearsPrepared: string | string[];
  residencyTaxYear: string | string[];
  servePeople: string | string[];
  eligibilityCriteriaWebpage?: string;
  bookingProcess: string | string[];
  bookingDaysHours: string;
  bookingContactPhone?: string;
  bookingContactEmail?: string;
  onlineBookingLink?: string;
  usefulOnlineBooking?: string;
  requiredDocuments?: string;
  helpWithMissingDocs: string | string[];
  taxPreparers?: string | string[];
  taxFilers?: string | string[];
  volunteerRoles?: string | string[];
  clinicCapacity?: string;
  additionalSupport?: string | string[];
  comments?: string;
  postalCodesServe?: string;
  createdDate: string;
  updatedDate: string;
  locations: Location[];
}
